# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        # Only run on PRs if the source branch is on someone else's repo
        if: ${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                java: [17]
            fail-fast: true
        steps:
            - uses: actions/checkout@v2.4.0
            - name: JDK ${{ matrix.java }}
              uses: actions/setup-java@v3.1.0
              with:
                  java-version: ${{ matrix.java }}
                  cache: 'gradle'
                  distribution: 'temurin'
            - name: Patch and build
              run: |
                  git config --global user.email "no-reply@github.com"
                  git config --global user.name "Github Actions"
                  ./gradlew applyPatches --stacktrace
                  ./gradlew createReobfBundlerJar --stacktrace
            - uses: actions/upload-artifact@v3
              with:
                name: my-artifact
                path: build/libs/islet-bundler-*-SNAPSHOT-reobf.jar
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                repo_token: "${{ secrets.GIT_RELEASE_TOKEN }}"
                automatic_release_tag: "latest"
                prerelease: true
                title: "Development Build"
                files: |
                  build/libs/*.jar
